version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 && start http://localhost:8000"